/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uppgift3;

import javax.swing.JOptionPane;

/**
 *
 * @author xdr
 */
public class HappyTrackerGui extends javax.swing.JFrame {

	private PackageEventList packageEventList;
	private PackageEventListModel packageEventListModel;
	private boolean focusGainedFirstTime;

	/**
	 * Creates new form HappyTrackerGui
	 */
	public HappyTrackerGui() {
		initComponents();
		focusGainedFirstTime = true;
		packageEventListModel = new PackageEventListModel();
		packageEventsList.setModel(packageEventListModel);
		packageEventList = new PackageEventList();
		packageEventListModel.setPackageEventList(packageEventList);

	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                searchButton = new javax.swing.JButton();
                searchTextField = new javax.swing.JTextField();
                trackingInfoScrollPane = new javax.swing.JScrollPane();
                packageEventsList = new javax.swing.JList();
                enterNumberLabel = new javax.swing.JLabel();
                trackingInformationLabel = new javax.swing.JLabel();
                packageInformationLabel = new javax.swing.JLabel();
                packageInfoScrollPane = new javax.swing.JScrollPane();
                packageInfoTextArea = new javax.swing.JTextArea();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                searchButton.setText("Search");
                searchButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                searchButtonActionPerformed(evt);
                        }
                });

                searchTextField.setText("34165454");
                searchTextField.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                searchTextFieldFocusGained(evt);
                        }
                });
                searchTextField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                searchTextFieldActionPerformed(evt);
                        }
                });

                packageEventsList.setModel(new javax.swing.AbstractListModel() {
                        String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
                        public int getSize() { return strings.length; }
                        public Object getElementAt(int i) { return strings[i]; }
                });
                trackingInfoScrollPane.setViewportView(packageEventsList);

                enterNumberLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
                enterNumberLabel.setText("Enter your tracking number:");

                trackingInformationLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
                trackingInformationLabel.setText("Tracking information: ");

                packageInformationLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
                packageInformationLabel.setText("Package Information:");

                packageInfoTextArea.setColumns(20);
                packageInfoTextArea.setRows(5);
                packageInfoScrollPane.setViewportView(packageInfoTextArea);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(trackingInfoScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(searchTextField)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(searchButton))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(enterNumberLabel)
                                                        .addComponent(packageInformationLabel)
                                                        .addComponent(trackingInformationLabel)
                                                        .addComponent(packageInfoScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(enterNumberLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(searchButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(packageInformationLabel)
                                .addGap(1, 1, 1)
                                .addComponent(packageInfoScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(trackingInformationLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(trackingInfoScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void searchTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTextFieldFocusGained
		if (focusGainedFirstTime) {
			searchTextField.setText("");
			focusGainedFirstTime = false;
		}
        }//GEN-LAST:event_searchTextFieldFocusGained

        private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
		// TODO add your handling code here:
		packageInfoTextArea.setText(null);
		String trackingInfoStr = null;
		int packageResponseCode = -1;
		try {
			HappyTrackerUtility.getPackageResponseCode(Integer.parseInt(searchTextField.getText()));
			packageResponseCode = HappyTrackerUtility.getPackageResponseCode(Integer.parseInt(searchTextField.getText()));
		} catch (NumberFormatException e) {
			JOptionPane.showMessageDialog(this, "You must enter a number.");
		}

		switch (packageResponseCode) {
			case 2:
				JOptionPane.showMessageDialog(this, "No such tracking number.");
				break;
			case 1:
				HappyTrackerUtility.getPackageInfo(Integer.parseInt(searchTextField.getText()));
				Package p = HappyTrackerUtility.getPackage(Integer.parseInt(searchTextField.getText()));
				PackageList packageList = HappyTrackerUtility.getPackageInfo(Integer.parseInt(searchTextField.getText()));

				for (int i = 0; packageList.packageListSize() > i; i++) {
					String packageInfoStr = packageList.getPackage(i).toString();
					packageInfoTextArea.append(packageInfoStr);
					packageEventList = packageList.getPackage(i).getPackageEventList();
					
					packageEventListModel.setPackageEventList(packageEventList);
					

				}
		}

        }//GEN-LAST:event_searchButtonActionPerformed

        private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_searchTextFieldActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(HappyTrackerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(HappyTrackerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(HappyTrackerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(HappyTrackerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new HappyTrackerGui().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel enterNumberLabel;
        private javax.swing.JList packageEventsList;
        private javax.swing.JScrollPane packageInfoScrollPane;
        private javax.swing.JTextArea packageInfoTextArea;
        private javax.swing.JLabel packageInformationLabel;
        private javax.swing.JButton searchButton;
        private javax.swing.JTextField searchTextField;
        private javax.swing.JScrollPane trackingInfoScrollPane;
        private javax.swing.JLabel trackingInformationLabel;
        // End of variables declaration//GEN-END:variables
}
